layout_spectrum: 0.749128
typography_spectrum: 0.1387909
color:
  saturation: 0.2085739
  lightness: 0.606239
  brandStrength: 0.3193481
  rhythmicContrast: 0.6734041
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: 7daytek
